<a href="https://colab.research.google.com/github/Tabbymargaret/kamilimu_assignments/blob/TabithaM_python_libraries_1/python_libraries_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Load dataset

In [3]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')
df.tail(7) #print the last 7 rowss

,order_id,quantity,item_name,choice_description,item_price
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

Print a summary of the DataFrame including the index dtype and column dtypes, non-null values, and memory usage. Comment on what you see.

In [4]:
df.info()
#

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

Comment on what you see.

In [5]:
""" The dataset has 4,622 observations and 5 columns.
order_id and quantity are numeric integers.
item_name, choice_description, and item_price are objects.
item_price should be converted to numeric because it currently includes the dollar sign.
choice_description has missing values, but item_price has no missing values. """

' The dataset has 4,622 observations and 5 columns.\norder_id and quantity are numeric integers.\nitem_name, choice_description, and item_price are objects.\nitem_price should be converted to numeric because it currently includes the dollar sign.\nchoice_description has missing values, but item_price has no missing values. '

Determine how many observations have missing item|price in the dataset.

In [6]:
missing_values = df['item_price'].isna().sum()
print(missing_values)

0

Print the names of all columns in the DataFrame.

In [7]:
# columns = df.columns.to_list
print(df.columns)

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

Identify which item_name appears most frequently in the orders.

In [8]:
top_item = df['item_name'].value_counts().head(1)
print(top_item)

item_name
Chicken Bowl    726
Name: count, dtype: int64

Determine how many distinct item_name values are present in the dataset.

In [9]:
distinct_items=df['item_name'].nunique()
#print(distinct_items)
print(distinct_items)

50

Create a new DataFrame containing only the rows where the item_name is 'Chicken Bowl'.

In [10]:
chicken_bowl_df = df[df['item_name']=='Chicken Bowl']
# print(chicken_bowl_df)
display(chicken_bowl_df)
# print(len(chicken_bowl_df))

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
...,...,...,...,...,...
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75

The 'item_price' column is currently a string (e.g., '$2.39'). Convert it to a float type. You'll need to remove the dollar sign and then convert the data type.

In [11]:
item_price_df = df['item_price'].str.replace('$', "")
item_price_df = item_price_df.astype(float)
display(item_price_df)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

After converting 'item_price' to a numerical type, calculate the average item_price across all orders.

In [12]:
item_price_df.mean()

np.float64(7.464335785374297)

Determine the total number of unique orders in the dataset based on the order_id column.

In [14]:
unique_order_id = df['order_id'].nunique()
print(unique_order_id)

1834

In [15]:
display(df['order_id'].drop_duplicates())

0          1
4          2
5          3
7          4
9          5
        ...
4610    1830
4612    1831
4615    1832
4617    1833
4619    1834
Name: order_id, Length: 1834, dtype: int64

Assuming each item_price (after conversion to float) is for a single quantity of that item, calculate the total revenue generated from all orders. Remember that the quantity column indicates how many of that item_name were ordered in that specific line item.

In [16]:
display(df.head(10))

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [31]:
# df['item_price'] = df['item_price'].str.replace('$', "")
df['item_price'] = df['item_price'].astype(float)
display(df.head(10))
df.dtypes

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
6,3,1,Side of Chips,NaN,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [34]:
df['total_revenue'] = df['quantity'] * df['item_price']
# total_revenue = df['total_revenue'].sum()
# print(total_revenue)
sorted_df = df.sort_values(by='total_revenue', ascending=False)
display(sorted_df.head(10))

,order_id,quantity,item_name,choice_description,item_price,total_revenue
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,663.75
4152,1660,10,Bottled Water,NaN,15.00,150.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00,140.00
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00,140.00
3887,1559,8,Side of Chips,NaN,13.52,108.16
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25,105.75
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75,101.25
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94,98.82
1255,511,3,Steak Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",27.75,83.25
3603,1443,3,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",27.75,83.25